blank_issues_enabled: true
contact_links:
  - name: Nous rejoindre sur Discord, pour toutes questions ou demandes
    url: http://discord.luuxis.fr
    about: Veuillez ne pas ouvrir d'issue autre que pour signaler des bugs
